WIP

diff --git a/.github/workflows/release-guard.yml b/.github/workflows/release-guard.yml
--- a/.github/workflows/release-guard.yml
+++ b/.github/workflows/release-guard.yml
@@ -27,7 +27,16 @@ jobs:
 
         echo "MAJOR_VERSION=$(echo $MAJOR_VERSION)" >> $GITHUB_OUTPUT;
         echo "BRANCH_MAJOR_VERSION=$(echo $BRANCH_MAJOR_VERSION)" >> $GITHUB_OUTPUT;
-        echo "VERSION_MISMATCH=$($MAJOR_VERSION != $BRANCH_MAJOR_VERSION)" >> $GITHUB_OUTPUT;
+
+        if [ "$MAJOR_VERSION" != "$BRANCH_MAJOR_VERSION" ]; then
+          echo "Mismatched versions! Aborting."
+          VERSION_MISMATCH=true;
+          # exit 1
+        else
+          echo "Versions match! Proceeding."
+          VERSION_MISMATCH=false;
+        fi
+        echo "VERSION_MISMATCH=$($VERSION_MISMATCH)" >> $GITHUB_OUTPUT;
       env:
         BRANCH_INPUT: ${{ inputs.branch_input }}
         RELEASE_NAME_INPUT: ${{ inputs.release_name_input }}
